config/routes.rb
Photogur::Application.routes.draw do
  

  
  resources :pictures

  root :to => 'pictures#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  # Rails knows this is a model (activerecord base subclass)
  # It knows there must be a db with the same title as this
  # so it looks for 'pictures' (plural). This is why the
  # Pictures.new command worked in rails console.

  # Also created an id. All models need some kind of id. Rails
  # made a number column automatically.

  # Can whitelist attributes for mass-assignment by adding to
  # list as in below example. Note: different from attr_accessor

  attr_accessible :title, :artist, :url, :copyrighted

  validates :title, :presence => {
    :message => "You must enter a photo title"
  }
  # presence validation is not needed on the URL because the RegExp would
  # capture that it was blank, thus not starting with http.
  validates :url,   {
    :presence => {
      :message => "You must enter a URL"
      },
    :format => {
      :with => /^https?:/, 
      :message => "Please enter a valid URL beginning with HTTP"
    }
  }

  scope :alphabetical, order("title ASC")
  scope :free, where(:copyrighted => false)

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

	# Most methods inside controllers are called actions
	## If index is empty, you can completely remove it and Rails will
	## still work. It knows the index.html exists.
	def index
		# Loading all pictures only where needed (index)
		if params[:free] == "yes"
			@pictures = Picture.free.alphabetical.all
		else
			@pictures = Picture.alphabetical.all
		end
	end

	def new
		@picture = Picture.new	
	end

	def create
		# Create in place of new was added before, but will always 
		# create a new object so it will always be true.
		@picture = Picture.new(params[:picture])
		if @picture.save
			redirect_to pictures_path
		else
			# There was an error on the form.
			flash.now[:error] = "Specified fields cannot be blank."

			render :new
		end
	end

	def show
		@picture = Picture.find params[:id]
	end

	def edit
		@picture = Picture.find params[:id]
	end

	def update
		@picture = Picture.find params[:id]

		if @picture.update_attributes(params[:picture])
			# Named routes (are methods) allow us to navigate app.
			# Can use just "@picture" without ID.
			# redirect_to picture_path(@picture.id)
			redirect_to @picture
			# We're passing picture and redirect_to method looks for
			# an ID.
		else
			# There was an error on the form.
			flash.now[:error] = "Specified fields cannot be blank."

			render :edit
		end
	end

	def destroy
		@picture = Picture.find params[:id]

		if @picture.destroy
			redirect_to pictures_path
		else
			redirect_to @picture
		end
	end

end

# params looks like = {
# 	:id => "4",
# 	:picture => {
# 		:title => "Title",
# 		:url => "http",
# 		:artist => "Someone"
# 	}
# }

# The form "for" picture, recognizes that it should just pass things in
# a way that the data can be accessed easily.

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav>
		<%= link_to "Show me a picture!", picture_path(Picture.all.sample)%>
		<%= link_to " | Free pictures only", pictures_path(:free => "yes") %>
		<%= link_to " | Home", pictures_path %>

	</nav>

	<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
	<div class="errors">
			<%= flash[:error] %>	
	</div>

	<%= form_for @picture do |f| %>
		<p>
			<div class="errors"><%= @picture.errors[:title].join(". ") %></div>	
			<%= f.label "Title" %>
			<%= f.text_field "title" %>	
		</p>
		<p>
			<%= f.label "Artist" %>
			<%= f.text_field "artist" %>
		</p>
		<p>
			<div class="errors"><%= @picture.errors[:url].join(". ") %></div>
			<%= f.label "URL" %>
			<%= f.text_field "url" %>
		</p>
		<p>
			<%= f.label "Copyrighted?" %>
			<%= f.check_box "copyrighted" %>
		</p>
		<p>
			<%= f.submit "Save" %>
		</p>

	<% end %>

app/views/pictures/edit.html.erb
<div class="escape-nav">
	<ul>
		<li><%= link_to "Return Home", pictures_path %></li>
		<li><%= link_to "View Image", picture_path(@picture) %></li>
	</ul>
</div>

<div class="display">
	<h1>Edit picture (ID <%= @picture.id %>)</h1>

	<%= render :partial => "form" %>
	<%= button_to "Delete", picture_path(@picture), :confirm => "Are you sure?", :method => :delete %>
</div>

app/views/pictures/index.html.erb
<!-- This is the body -->
<!-- Find header, etc. in application.html.erb -->
<!-- <header>
	<h1>PHOTOGUR</h1>
</header> -->

<div class="sectionheader">
	<h1>Picture Listing</h1>
	<div id="new-link">
		<%= link_to "Add a Photo", new_picture_path %>
	</div>
	<div class="clear"></div>
</div>

<!-- "-" says run something in ruby, but don't print the result -->
<%- @pictures.each do |picture| %>
		<div class="display">
			<h2><%= picture.title %></h2>
			<h4><%= picture.artist %></h4>
			<div class="photo-nav">
				<a href="<%= picture_path(picture) %>">View Photo</a> | <a href="<%= edit_picture_path(picture) %>">Edit</a>
			</div>
			<div class="imageframe">
				<% if picture.copyrighted %>
				<div class="copyrighted">
					<p>Image is copyrighted by its original author.</p>
				</div>
				<div class="clear"></div>
				<% end %>
				<div class="image">
					<%= link_to picture_path(picture) do %>
					<%= image_tag picture.url %>
					<% end %>
				</div>
			</div>
		</div>
<% end %>	
<!-- with = t would print out more than you want -->

app/views/pictures/new.html.erb
<div class="escape-nav">
	<ul>
		<li><%= link_to "Return Home", pictures_path %></li>
	</ul>
</div>

<div class="display">
	<h1>Add a picture</h1>

	<%= render :partial => "form" %>
</div>

app/views/pictures/show.html.erb
<div class="escape-nav">
	<ul>
		<li><%= link_to "Return Home", pictures_path %></li>
		<li><%= link_to "Edit", edit_picture_path(@picture) %></li>
	</ul>
</div>

<div class="display">
	<h2><%= @picture.title %></h2>
	<h4><%= @picture.artist %></h4>

	<%= link_to picture_path(@picture) do %>
		<%= image_tag @picture.url %>
	<% end %>
</div>